jdbc.driverClassName=org.postgresql.Driver
jdbc.url=${SCHEDULE_DB_URL:jdbc:postgresql://localhost:5432/schedule}
jdbc.username=${SCHEDULE_DB_USERNAME:postgres}
jdbc.password=${SCHEDULE_DB_PASSWORD:postgres}
