app.db.vendor=${APP_DB_VENDOR:postgres}
jwt.secret=${JWT_SECRET:}
jwt.issuer=${JWT_ISSUER:jsAdmin}
admin-service.base-url=${ADMIN_SERVICE_BASE_URL:http://localhost:8081}
kakao.rest-api-key=${KAKAO_REST_API_KEY:49dc1e9096727e68bd526d10c0f7af01}
kakao.javascript-key=${KAKAO_JAVASCRIPT_KEY:44d0fd2c6b9de315c9635d8e297dc9a4}
juso.confirmation-key=${JUSO_CONFIRMATION_KEY:devU01TX0FVVEgyMDI2MDQxODA5MTkzNzExNzk1Njk=}
